# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunnel" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "1d469ae1bbf2d4a014e786582828fe3d8b41fc73c4c1287cb6f688f63ab999dd"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e58763df7cad54fe0ba5c4881d4145fc0ce095a1962411cc8fd8448481c6d931"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6770ba48008bca15f9ebcf453e0017c447eb89271473dc5ebcf7579f481e3da2"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "16d23b172eac47571f989d563be0cc425b6fc72fc75bc620f87e62e0b0ae5d46"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_linux_arm64.tar.gz"
    end
  end

  name "tunnel"
  desc "Self-hosted ngrok alternative — your own tunnel server and client"
  homepage "https://github.com/ur-link/tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunnel"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tunnel"]
    end
  end

  # No zap stanza required

end
