# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunnel" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "eacb950463e430e908c6d51018a065460bc0536ec17013f785576de0291dd869"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7fba963740c6c7de89da010ae6a3d83f8219e85cefe0eca8cf81ddeb380f7a2a"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aadd930f4b2583f1f27a95940d92820204f593e1cb5a43d0b075df1de0d6bc08"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bba97602e92e43b0d6bd6c0cf3adfdd4d9ef289431313b14eaba5c21d985a0ab"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_linux_arm64.tar.gz"
    end
  end

  name "tunnel"
  desc "Self-hosted ngrok alternative — your own tunnel server and client"
  homepage "https://github.com/ur-link/tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunnel"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tunnel"]
    end
  end

  # No zap stanza required

end
