# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunnel" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "da43c15e3fbcbcf825d950a809bf219013ec86f39c071a407e78e0b760b80828"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1b511dfe98fccb32ff6f77e719a9d8b8cf2c6f5ed4473f4ce8ec90f4fea2c3f8"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e9636e3aaf7e35bfa4181606668b8fd236506eb28f8052b4c5ba4b932f90a92e"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "09ea18d20947be48634d7c6eefb6c0e6c6f4eacb15fbbfcb1d9c5f1c293387c2"
      url "https://github.com/ur-link/tunnel/releases/download/v#{version}/tunnel_linux_arm64.tar.gz"
    end
  end

  name "tunnel"
  desc "Self-hosted ngrok alternative — your own tunnel server and client"
  homepage "https://github.com/ur-link/tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunnel"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tunnel"]
    end
  end

  # No zap stanza required

end
